version: '3.8'
services:
  db:
    container_name: pg_container_13.1
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: tweet_user
      POSTGRES_PASSWORD: tweet123!@
      POSTGRES_DB: tweetdb_dev
    ports:
      - "5459:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: